from __future__ import annotations

from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]

SPRINT_DIR = REPO_ROOT / "docs" / "sprint_1"
OUTPUT_PATH = (
    REPO_ROOT
    / "docs"
    / "repo-governance"
    / "generated"
    / "CLEANUP_INVENTORY_SPRINT_1_GENERATED.md"
)


KEEP_ACTIVE_EXACT = {
    "SPRINT_1_ACTION_PACK.md",
    "SPRINT_1_ADMISSION_CHECKLIST.md",
    "SPRINT_1_IMPLEMENTATION_BOUNDARY.md",
    "SPRINT_1_FIRST_SLICE_PLAN.md",
    "SPRINT_1_CLOSURE_READINESS_REVIEW.md",
    "SPRINT_1_EXIT_AUDIT_SNAPSHOT.md",
    "SPRINT_1_PHASE_A_EXIT_AUDIT_SNAPSHOT.md",
    "SPRINT_1_PHASE_A_REPOSITORY_VERIFICATION_NOTE.md",
}

REVIEW_KEYWORDS = (
    "ADMISSION_REVIEW",
    "ENTRY_CONTROL",
    "READINESS",
    "VERIFICATION",
    "ADMISSION",
    "BOUNDARY",
)

ARCHIVE_KEYWORDS = (
    "SCAFFOLD_PASS_CLOSURE_NOTE",
    "SCAFFOLD_CLOSURE_SUMMARY_NOTE",
    "SCHEMA_BOUNDARY_PASS_CLOSURE_NOTE",
    "CONTRACT_BOUNDARY_PASS_CLOSURE_NOTE",
    "UNIT_TEST_PASS_CLOSURE_NOTE",
    "PASS_CLOSURE_NOTE",
    "TEST_SANITY_REFRESH",
)


def classify_file(filename: str) -> tuple[str, str, str]:
    """Return category, reason, and suggested destination for a Sprint 1 doc."""

    if filename in KEEP_ACTIVE_EXACT:
        return (
            "KEEP_ACTIVE",
            "Sprint 1 summary, admission, readiness, boundary, or exit-audit document.",
            "docs/sprint_1/",
        )

    if any(keyword in filename for keyword in ARCHIVE_KEYWORDS):
        return (
            "ARCHIVE_CANDIDATE",
            "Granular closure, scaffold, unit-test, preview, or test-sanity pass note.",
            f"docs/archive/old-sprint-material/sprint_1/{filename}",
        )

    if any(keyword in filename for keyword in REVIEW_KEYWORDS):
        return (
            "REVIEW",
            "Potentially important control, readiness, admission, verification, or boundary document.",
            "PENDING_REVIEW",
        )

    return (
        "REVIEW",
        "No safe automatic classification rule matched.",
        "PENDING_REVIEW",
    )


def escape_markdown(value: str) -> str:
    return value.replace("|", "\\|")


def generate_report() -> str:
    if not SPRINT_DIR.exists():
        raise FileNotFoundError(f"Sprint 1 docs folder not found: {SPRINT_DIR}")

    files = sorted(path for path in SPRINT_DIR.iterdir() if path.is_file())

    rows = []
    counts: dict[str, int] = {}

    for path in files:
        category, reason, destination = classify_file(path.name)
        counts[category] = counts.get(category, 0) + 1
        rows.append(
            "| `{file}` | `{category}` | {reason} | `{destination}` | no |".format(
                file=escape_markdown(path.name),
                category=category,
                reason=escape_markdown(reason),
                destination=escape_markdown(destination),
            )
        )

    summary_lines = [
        "# Generated Cleanup Inventory — Sprint 1 Documentation",
        "",
        "Status: Generated read-only inventory report.",
        "",
        "## Purpose",
        "",
        "This report was generated by `scripts/cleanup_inventory.py`.",
        "",
        "The report classifies files in `docs/sprint_1/` for human review before any archive movement.",
        "",
        "This report does not move files.",
        "",
        "This report does not delete files.",
        "",
        "This report does not edit source code, tests, workflows, or existing documentation.",
        "",
        "## Source Folder",
        "",
        "- `docs/sprint_1/`",
        "",
        "## Output File",
        "",
        "- `docs/repo-governance/generated/CLEANUP_INVENTORY_SPRINT_1_GENERATED.md`",
        "",
        "## Category Counts",
        "",
    ]

    for category in sorted(counts):
        summary_lines.append(f"- `{category}`: {counts[category]}")

    summary_lines.extend(
        [
            "",
            "## Inventory Table",
            "",
            "| File | Suggested category | Reason | Suggested destination | Move now? |",
            "| --- | --- | --- | --- | --- |",
            *rows,
            "",
            "## Review Rule",
            "",
            "No file should be moved based only on this generated report.",
            "",
            "A human review must approve any movement batch before files are archived.",
            "",
            "## No-Drift Confirmation",
            "",
            "- Archive movement: not performed by this script.",
            "- Deletion: not performed by this script.",
            "- Source edits: not performed by this script.",
            "- Test edits: not performed by this script.",
            "- Workflow edits: not performed by this script.",
            "- Functional Local Prototype Engine work: not started by this script.",
            "",
        ]
    )

    return "\n".join(summary_lines)


def main() -> None:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(generate_report(), encoding="utf-8")
    print(f"Generated Sprint 1 cleanup inventory: {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
